version: '3.8'

services:
  nginx-42:
    build: ./requirements/nginx
    image: nginx-42
    container_name: nginx-42
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - wordvol:/var/www/html
    networks:
      - Inception_net
    depends_on:
      - wordpress-site

  maria-database:
    build: ./requirements/mariadb
    image: maria-database
    container_name: maria-database
    env_file:
      - .env
    restart: on-failure
    volumes:
      - mariavol:/var/lib/mysql
    networks:
      - Inception_net
    healthcheck:
      test:  [ "CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
  
  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file:
      - .env
    restart: on-failure
    volumes:
      - wordvol:/var/www/html
    networks:
      - Inception_net
    depends_on:
      maria-database:
        condition: service_healthy
  
volumes:
  mariavol:
    name: mariavol
    driver_opts:
      type: none
      device: /home/luis/data/database
      o: bind
  wordvol:
    name: wordvol
    driver_opts:
      type: none
      device: /home/luis/data/wordpress
      o: bind

networks:
  Inception_net:
    name: Inception

# version: '3.8'

# services:
#   nginx-server:
#     build: ./requirements/nginx
#     image: nginx-server
#     container_name: nginx-server
#     ports:
#       - 443:443
#     depends_on:
#       - wordpress-site
#     volumes:
#       - wp:/var/www/html
#     networks:
#       - inception
#     restart: on-failure

#   mariadb-data:
#     build: ./requirements/mariadb
#     image: mariadb-data
#     container_name: mariadb-data
#     env_file:
#       - .env
#     volumes:
#       - db:/var/lib/mysql
#     networks:
#       - inception
#     restart: on-failure
#     healthcheck:
#       test: [ "CMD", "mysqladmin", "ping", "--silent"]
#       interval: 5s
#       timeout: 30s
#       retries: 10
#       start_period: 5s
  
#   wordpress-site:
#     build: ./requirements/wordpress
#     image: wordpress-site
#     container_name: wordpress-site
#     env_file:
#       - .env
#     depends_on:
#       mariadb-data:
#         condition: service_healthy
#     volumes:
#       - wp:/var/www/html
#     networks:
#       - inception
#     restart: on-failure


# volumes:
#   db:
#     name: db
#     driver_opts:
#       type: none
#       device: /home/lucas-ma/data/mysql
#       o: bind
#   wp:
#     name: wp
#     driver_opts:
#       type: none
#       device: /home/lucas-ma/data/wordpress
#       o: bind

# networks:
#   inception:
#     name: inception